title: Jonathan Blades
description: Software developer, writer and maker based near Glasgow, Scotland.

url: "https://jonoblades.github.io"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/og-image.png
        width: 1200
        height: 630
  - scope:
      path: ""
      type: fifty-words
    values:
      layout: default
  - scope:
      path: ""
      type: writing
    values:
      layout: default

author:
  name: Jonathan Blades

plugins:
  - jekyll-feed

collections:
  writing:
    title: "Writing"
    output: true
    permalink: /writing/:name/
  fifty-words:
    title: "Fifty Words"
    output: true
    permalink: /fifty-words/:name/

feed:
  icon: "/assets/favicon-512x512.png"
  logo: "/assets/favicon-512x512.png"
  collections:
    writing:
      path: "/writing/feed.xml"
    fifty-words:
      path: "/fifty-words/feed.xml"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - .jekyll-cache
  - .jekyll-metadata
  - node_modules
