title: Jonathan Blades
description: Software developer, writer and maker based near Glasgow, Scotland.

url: "https://jonoblades.github.io"
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - .jekyll-cache
  - .jekyll-metadata
  - node_modules
