source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-archives"
gem "jekyll-feed"
gem "jekyll-paginate-v2"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "kramdown-parser-gfm"
gem "webrick"